fix refresh_token issue
marklagendijk/node-toogoodtogo-watcher pull request #122
Opened 2021-12-06 19:33 UTC by DzianisMakeichyk

Fix issue #121

2021-12-07 14:00 UTC, beatbrot requested changes
I don't really understand this PR. It doesn't seem to fix the actual login process.

This PR might only work if you already have a valid refresh token from the past.

2021-12-07 14:00 UTC, beatbrot commented on lib/api.js
> +function authPoll(polling_id) {
It seems like this method is not called anywhere. Surely this PR can't fix our problem, right?

2021-12-07 16:15 UTC, c0lumb0 commented
> I don't really understand this PR. It doesn't seem to fix the actual login process.
> 
> This PR might only work if you already have a valid refresh token from the past.

Yup, just gave it a try. Works when there is a valid refresh token from the past.

2021-12-07 19:22 UTC, DzianisMakeichyk commented
@c0lumb0 @c0lumb0 Hard to say anything, cause this code is copy-pasted from the issue and this code helped for me :)

2021-12-07 20:41 UTC, c0lumb0 commented
> @c0lumb0 @c0lumb0 Hard to say anything, cause this code is copy-pasted from the issue and this code helped for me :)

For me it worked when I added the tokens again...I guess you also still have them in your config? :)

2021-12-11 14:00 UTC, marklagendijk commented
I merged #123 instead.

2021-12-11 14:00 UTC, closed without merging